### ISSUE TITLE
字体列表变量使用 `body` 会导致插件 `自定义字体` 失效

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [terwer/siyuan-theme-zhihu#100]
https://github.com/terwer/siyuan-theme-zhihu/blob/a524015c1a61d56762c65ecf4a05e55bab7a6dbf/style/theme/basic/index.styl#L31-L38

https://github.com/Zuoqiu-Yingyi/siyuan-plugin-custom-fonts/issues/13

最好使用 `:root` 或者 `html` 设置字体列表 CSS 变量

**Comment by terwer** [comment]
已修复
