### ISSUE TITLE
文字在被标记后，字体大小相比无样式文字过小

### ISSUE THREAD

**Issue by HerrHuang** [terwer/siyuan-theme-zhihu#101]
问题：字体在被标记后过小（绿色部分），在被标记时，需要同时加粗，才能保持与其他无样式文字同等大小（黄色部分）
需求：标记不要改变文字大小
客户端：MacOS14，SiYuan：v2.10.15，主题版本：v0.0.15
<img width="766" alt="image" src="https://github.com/terwer/siyuan-theme-zhihu/assets/64797182/051ded9f-959d-44d8-9efa-a9269dc496f5">

**Comment by terwer** [comment]
已修复如下，看看是否满意：

**Comment by HerrHuang** [comment]
很棒！辛苦啦 T 大。新版本何时发布？

**Comment by terwer** [comment]
已经发布。 `01.0`
