### ISSUE TITLE
思源笔记上无法使用，提示不兼容

### ISSUE THREAD

**Issue by yuhen562** [terwer/siyuan-theme-zhihu#74]
在思源笔记上无法使用，提示不兼容，怎么解决呢？

**Comment by terwer** [comment]
你的版本是多少呢

**Comment by yuhen562** [comment]
我的版本时【当前版本 v2.9.0】。

**Comment by terwer** [comment]
主题完全是css，只影响外玩，不会修改任何功能，因此不可能出现提示不兼容的东西。
你看看是不是有自定义js片段或者插件的呢。应该不是我这个主题的问题。你试试禁用所有插件和自定义js片段
