### ISSUE TITLE
分割线与白色背景颜色相近难以

### ISSUE THREAD

**Issue by peixxxxxx** [terwer/siyuan-theme-zhihu#77]
![image](https://github.com/terwer/siyuan-theme-zhihu/assets/97796097/30fbeac3-3c92-49fc-8184-19756ebd1c19)

上图是思源里面敲下三个【-】横杠会自动变成的分割线，但是颜色和背景太接近了，完全区分不开。

上图是用鼠标选中时的情况，未选中时只能看到一篇白色

**Comment by terwer** [comment]
已修复
