### ISSUE TITLE
如何把大纲线条恢复成默认的样子？

### ISSUE THREAD

**Issue by JARVISia** [terwer/siyuan-theme-zhihu#99]
![image](https://github.com/terwer/siyuan-theme-zhihu/assets/16850140/4f5d8d76-1d8d-41f7-bd1c-d44733cf9e09)
想把大纲的线恢复成默认的样子，请问需要添加什么代码？

**Comment by terwer** [comment]
对于列表转闪卡，这块做了修改。如果不是闪卡，列表未改。

```
.card__block .protyle-wysiwyg .li[data-node-id][custom-riff-decks] {
  margin-top: 12px;
}
.protyle-wysiwyg .li[data-node-id][custom-riff-decks] {
  border-left: none !important;
  border-radius: 0;
  box-shadow: 0 0 5px 2px #ff6a6a !important;
  padding: 12px;
  background-clip: padding-box;
}
.protyle-wysiwyg .li[data-node-id][custom-riff-decks]::before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 0.15em;
  height: 100%;
  background-color: #ff6a6a;
  box-shadow: 0 0 5px 2px var(--b3-card-warning-background);
}
```

下面是修改，可死党还原。

**Comment by JARVISia** [comment]
> 对于列表转闪卡，这块做了修改。如果不是闪卡，列表未改。
> 
> ```css
> .card__block .protyle-wysiwyg .li[data-node-id][custom-riff-decks] {
>   margin-top: 12px;
> }
> .protyle-wysiwyg .li[data-node-id][custom-riff-decks] {
>   border-left: none !important;
>   border-radius: 0;
>   box-shadow: 0 0 5px 2px #ff6a6a !important;
>   padding: 12px;
>   background-clip: padding-box;
> }
> .protyle-wysiwyg .li[data-node-id][custom-riff-decks]::before {
>   content: "";
>   position: absolute;
>   top: 0;
>   left: 0;
>   width: 0.15em;
>   height: 100%;
>   background-color: #ff6a6a;
>   box-shadow: 0 0 5px 2px var(--b3-card-warning-background);
> }
> ```
> 
> 上面是修改，可适当还原。

我的意思是，默认主题是直接显示大纲线的，你的这个主题是鼠标放在这里才会显示大纲竖线，离开就不显示。我想知道怎么让它默认显示。谢谢

**Comment by terwer** [comment]
找到问题了，已修复。晚点更新 `0.1.1`，这块会还原成默认。
